name: Build and Push Multi-Arch Docker Images

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pinkfuwa/llumen
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/pinkfuwa/llumen:amd64
          build-args: |
            ARCH=x86_64

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/pinkfuwa/llumen:arm64
          build-args: |
            ARCH=aarch64

      - name: Get Digests
        id: digests
        run: |
          IMAGE=ghcr.io/pinkfuwa/llumen

          DIGEST_AMD64=$(docker buildx imagetools inspect ${IMAGE}:amd64 --format '{{json .Manifest.Digest}}' | tr -d '"')
          DIGEST_ARM64=$(docker buildx imagetools inspect ${IMAGE}:arm64 --format '{{json .Manifest.Digest}}' | tr -d '"')

          echo "amd64_digest=${DIGEST_AMD64}" >> "$GITHUB_OUTPUT"
          echo "arm64_digest=${DIGEST_ARM64}" >> "$GITHUB_OUTPUT"

      - name: Create and Push Manifest
        run: |
          IMAGE=ghcr.io/pinkfuwa/llumen

          docker manifest create ${IMAGE}:latest \
            ${IMAGE}@${{ steps.digests.outputs.amd64_digest }} \
            ${IMAGE}@${{ steps.digests.outputs.arm64_digest }}

          docker manifest push ${IMAGE}:latest
