name: Build and Push Multi-Arch Docker Images

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pinkfuwa/llumen
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/pinkfuwa/llumen:amd64
          build-args: |
            ARCH=x86_64

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/pinkfuwa/llumen:arm64
          build-args: |
            ARCH=aarch64

      - name: Create and push manifest
        run: |
          docker manifest create ghcr.io/pinkfuwa/llumen:${{ github.ref_name }} \
            ghcr.io/pinkfuwa/llumen:amd64 \
            ghcr.io/pinkfuwa/llumen:arm64
          docker manifest push ghcr.io/pinkfuwa/llumen:${{ github.ref_name }}

          # Also push latest tag
          docker manifest create ghcr.io/pinkfuwa/llumen:latest \
            ghcr.io/pinkfuwa/llumen:amd64 \
            ghcr.io/pinkfuwa/llumen:arm64
          docker manifest push ghcr.io/pinkfuwa/llumen:latest
