[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = "1.1.14"
serde_json = "1.0.141"
typeshare = "1.0.4"

[dependencies.serde]
version = "1.0.219"
features = ["derive"]
